name: NoAdvertisingPE
main: Vaivez66\NoAdvertisingPE\NoAdvertising
version: 1.1.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: POSTWORLD
author: [VMPE Development team]
description: "Stop those advertiser!"
commands:
  na:
    description: "Main command"
    usage: "/na <add|remove|list> [domain]"
permissions:
  no.advertising.pe:
    description: "Permission to perform command"
    default: op
  no.advertising.pe.bypass:
    description: "Permission to bypass from blocking"
    default: false
