name: NoAskingPE
main: Vaivez66\NoAdvertisingPE\NoAskingPE
version: 1.0.0
api: [3.0.0-ALPHA6, 3.0.1]
load: POSTWORLD
authors: [Zeao]
description: "Stop those Askers who ask for stuff on your server!"
commands:
  nask:
    description: "Main command"
    usage: "/na <add|remove|list> [question]"
permissions:
  no.asking.pe:
    description: "Permission to perform command"
    default: op
  no.asking.pe.bypass:
    description: "Permission to bypass from blocking"
    default: false
