
# Available types:
#   - broadcast
#   - block
#   - kick
type: block
# The message that will send
# You can use {player} to mention their name
message: '{RED}Please do not ask this question!'
# Blocked domain names
domain:
  - ".me"
  - ".com"
  - ".net"
# The domains that allowed to use
allowed.domain:
  - "yourserver.com"
  - "pocketmine.net"
# If true, it will detect a sign
detect.sign: true
# Lines that will change if player asks on sign
lines:
  - '============='
  - 'No asking!'
  - '============='
  - ''
# The command that will be protected from asking
blocked.cmd:
  - "/me"
  - "/tell"
